export const ACCEPT_DOG = 'accept_dog'
export const ACCEPT_DOGTYPE = 'accept_dogType'
export const ACCEPT_DOGTYPEDET='accept_dogtypedet'
export const ACCEPT_CATEGORY='accept_category'
export const ACCEPT_ALLBRAND='accept_allbrand'
